import { bootstrapApplication } from '@angular/platform-browser';
import { addIcons } from 'ionicons';
import {
  add,
  addCircleOutline,
  arrowBack,
  arrowDown,
  arrowForward,
  arrowUp,
  camera,
  chatbubbleEllipses,
  checkmark,
  checkmarkCircle,
  chevronDown,
  chevronForward,
  close,
  compass,
  copy,
  copyOutline,
  createOutline,
  heart,
  heartOutline,
  helpCircleOutline,
  imagesOutline,
  link,
  lockClosed,
  people,
  personAdd,
  refresh,
  restaurant,
  rocket,
  shareSocial,
  shieldCheckmark,
  sparkles,
  trophy,
  trashOutline,
} from 'ionicons/icons';
import { AppComponent } from './app/app.component';
import { appConfig } from './app/app.config';

addIcons({
  add,
  addCircleOutline,
  arrowBack,
  arrowDown,
  arrowForward,
  arrowUp,
  camera,
  chatbubbleEllipses,
  checkmark,
  checkmarkCircle,
  chevronDown,
  chevronForward,
  close,
  compass,
  copy,
  copyOutline,
  createOutline,
  heart,
  heartOutline,
  helpCircleOutline,
  imagesOutline,
  link,
  lockClosed,
  people,
  personAdd,
  refresh,
  restaurant,
  rocket,
  shareSocial,
  shieldCheckmark,
  sparkles,
  trophy,
  trashOutline,
});

bootstrapApplication(AppComponent, appConfig).catch((error: unknown) => {
  console.error('Crush Club bootstrap failed', error);
});
